### ISSUE TITLE
Release is compiled as Debug and requires msvcr120d.dll

### ISSUE THREAD

**Issue by cw2k** [ThunderCls/xLCB#2]
Plz compile it as release and maybe statically linked.
... ands also some include x64.

Workaround
Works also with msvcr100d.dll or msvcr110d.dll when you rename/copy them msvcr120d.dll.
( I also tried msvcr71d.dll and msvcrd.dll but these are to old / don't work). 
... and of course if you've all the Visual Studio stuff downloaded and installed you can compile it ya own.

**Comment by ThunderCls** [comment]
you could download the project and compile yourself in release mode till I get appveyor set up for this
